commands/stonks.js
=> Add price change with colors to stonks

commands/8ball.js
=> Added 8ball command

commands/rank.js
=> Initial iteration for .rank command

package-lock.json, package.json
=> Update package with TNY discord-bot information

commands/gif.js
Closes #22 
So I just used the Search endpoint instead and randomly chose a result.
Do you guys think it's ok to replace the old implementation or would we rather add a separate command for this endpoint?
=> Use Search API instead of Random API for gif

commands/rank.js
=> Reverse displayed rank list

commands/8ball.js, commands/gif.js, commands/isitracist.js, commands/mylevel.js, commands/ping.js, commands/stonks.js
=> changed names, lets see brandon test

commands/rank.js, modules/TableBoi.js
Display rank leaderboard using TableBoi
=> Created TableBoi for building ascii tables.

modules/TableBoi.js
=> Fixed table display issue

commands/dota.js, commands/rank.js, modules/functions.js, package-lock.json, package.json
Created the dal and several commands executing against the opendota api.
Example bot executions:
https://imgur.com/a/V63Wotu
=> Initial dota bot

commands/dota.js, index.js, modules/DiscordClientAwareScheduler.js, modules/OpenDotaClient.js, modules/TimeFormatters.js, package-lock.json, package.json, schedulables/dotaMatchAnnouncerPoller.js
Added the concept of schedulers and schedulables
Have a schedulable that polls openDota for any recent matches that are played by registered dota players and announces them to their configured discord channels.
Minor refactoring (created a rate limited open dota client)
https://imgur.com/a/KoN5cRp
=> Dota match summary poller

commands/dota.js, commands/rank.js, modules/functions.js
=> [dota] added deregister and whois commands

commands/rank.js, commands/rez.js, modules/CampingReservationClient.js, modules/TableBoi.js, schedulables/ReservationAvailabilityPoller.js
Rank: added "reset" subcommand
Rez: Now checks multiple campsites, displays results as an embed
=> Enhance reservation checker to check multiple campsites.

schedulables/ReservationAvailabilityPoller.js
Remove logging, add null-check
=> Remove logging, add null-check

commands/roles.js
Resolves #79
Added functionality:
```
= USAGE =
.roles create [role]   :: Create a new role
.roles join [role]     :: Join a role
.roles leave [role]    :: Leave a role
.roles list            :: Displays all available roles
```
=> Add initial roles command

commands/poll.js, modules/ArgParser.js, modules/poll.js, package-lock.json, package.json
polling is fun my dudes
tests:
https://imgur.com/a/yWEK4L2
=> Add command for polling

commands/poll.js, modules/Poll.js
Tests
https://imgur.com/a/KPH1FMw
=> set guild emotes to be default emojis for poll options

index.js, modules/Patcher.js, patches/p1.js
On first run
patches begin
Applying patch p1.js
rolesV1-pre: {"name":"rolesdata","version":"5.8.2","exportDate":1612115017819,"keys":[{"key":"143146071814569986","value":["tarkov","tnydotatoes","theboiis"]}]}
rolesV2-pre: {"name":"rolesdatav2","version":"5.8.2","exportDate":1612115017820,"keys":[]}
rolesV1-post: {"name":"rolesdata","version":"5.8.2","exportDate":1612115017822,"keys":[{"key":"143146071814569986","value":["tarkov","tnydotatoes","theboiis"]}]}
rolesV2-post: {"name":"rolesdatav2","version":"5.8.2","exportDate":1612115017823,"keys":[{"key":"143146071814569986:tarkov","value":{"name":"tarkov","guildId":"143146071814569986","description":null,"channelId":null}},{"key":"143146071814569986:tnydotatoes","value":{"name":"tnydotatoes","guildId":"143146071814569986","description":null, …
=> Introduce a patching framework to handle updating roles backing data

commands/rank.js
=> Grab old rank BEFORE its set to the new rank 

.eslintrc.js, .gitignore, commands/roles.js
Reverts tnygaming/discord-bot#117
=> Revert "Role Create Channel"
